"""Add class Coordinate.

Revision ID: 421e11d5c722
Revises: 2668c987f705
Create Date: 2022-06-20 20:12:58.878834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421e11d5c722'
down_revision = '2668c987f705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordinate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coordinate')
    # ### end Alembic commands ###
