"""New

Revision ID: 55f757a26d67
Revises: 893790f14be0
Create Date: 2022-07-15 19:08:47.264531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f757a26d67'
down_revision = '893790f14be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detail', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail', sa.Column('image', sa.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###
