"""Initial migration.

Revision ID: 589538ed5005
Revises: 
Create Date: 2022-06-12 21:19:28.621574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589538ed5005'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_liste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.Unicode(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_liste')
    # ### end Alembic commands ###
