"""Refactoring model Deatail -- DescriptionRoute

Revision ID: 69f40dea0053
Revises: 55f757a26d67
Create Date: 2022-09-15 21:11:06.477637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f40dea0053'
down_revision = '55f757a26d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('description_route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('description_start', sa.Text(), nullable=False),
    sa.Column('description_basic', sa.Text(), nullable=False),
    sa.Column('routestart', sa.Text(), nullable=False),
    sa.Column('workingmode', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('route_id', sa.INTEGER(), nullable=False),
    sa.Column('description_start', sa.TEXT(), nullable=False),
    sa.Column('description_basic', sa.TEXT(), nullable=False),
    sa.Column('routestart', sa.TEXT(), nullable=False),
    sa.Column('workingmode', sa.TEXT(), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('description_route')
    # ### end Alembic commands ###
