"""new class Detail v1.2

Revision ID: 6ee741a2f975
Revises: 81d338581ca4
Create Date: 2022-06-22 23:10:57.840914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee741a2f975'
down_revision = '81d338581ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail', sa.Column('image', sa.Unicode(length=128), nullable=False))
    op.drop_column('detail', 'imagecarousels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail', sa.Column('imagecarousels', sa.VARCHAR(length=128), nullable=False))
    op.drop_column('detail', 'image')
    # ### end Alembic commands ###
