"""class Detail v1.1 

Revision ID: 81d338581ca4
Revises: 6a813c626fb7
Create Date: 2022-06-22 22:57:16.472124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d338581ca4'
down_revision = '6a813c626fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail', sa.Column('image', sa.Unicode(length=128), nullable=False))
    op.drop_column('detail', 'imagecarousels')
    op.drop_column('detail', 'order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail', sa.Column('order', sa.INTEGER(), nullable=False))
    op.add_column('detail', sa.Column('imagecarousels', sa.VARCHAR(length=128), nullable=False))
    op.drop_column('detail', 'image')
    # ### end Alembic commands ###
