"""empty message

Revision ID: 93d9fb90e302
Revises: 988c73d08cad
Create Date: 2022-07-01 19:56:52.661291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d9fb90e302'
down_revision = '988c73d08cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visual', sa.Column('image', sa.Unicode(length=128), nullable=False))
    op.drop_column('visual', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visual', sa.Column('img', sa.VARCHAR(length=128), nullable=False))
    op.drop_column('visual', 'image')
    # ### end Alembic commands ###
