"""empty message

Revision ID: 988c73d08cad
Revises: ace35c4c2680
Create Date: 2022-06-29 17:04:48.248086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988c73d08cad'
down_revision = 'ace35c4c2680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.Unicode(length=128), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('detail', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detail', 'order')
    op.drop_table('visual')
    # ### end Alembic commands ###
