"""Visual db.

Revision ID: dc2dead23735
Revises: 8a6fd7e9cacb
Create Date: 2022-06-24 21:01:19.274701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2dead23735'
down_revision = '8a6fd7e9cacb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.Unicode(length=128), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visual')
    # ### end Alembic commands ###
