"""Add json format.

Revision ID: fb86875e52ef
Revises: f8d5022b4054
Create Date: 2022-07-02 18:42:15.781296

"""
from alembic import op
import sqlalchemy as sa
from webapp.admin import JsonEncodedDict

# revision identifiers, used by Alembic.
revision = 'fb86875e52ef'
down_revision = 'f8d5022b4054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('way',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('fancy_name', JsonEncodedDict(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('way')
    # ### end Alembic commands ###
